default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: 
  password:
  host: 

development:
  <<: *default
  database: csv_dev

test:
  <<: *default
  database: csv_test

production:
  <<: *default
  database: csv_prod
